### ISSUE TITLE
Suggested tags are not first in tag lists

### ISSUE THREAD

**Issue by camallen** [zooniverse/Talk-Api#123]
https://www.zooniverse.org/projects/birgus2/western-shield-camera-watch/talk/276/428304?comment=723878

As per the report from talk, some suggested project tags match existing tags (trigram?) and don't sort up the list properly. We should fix this in the tag completion sql https://github.com/zooniverse/Talk-Api/blob/1317d3b605a8e9476271fbf907144ff723c98dce/lib/tag_completion.rb#L13

**Comment by camallen** [comment]
Another idea from Yshish is to allow project teams to mark tags as invalid, https://www.zooniverse.org/projects/birgus2/western-shield-camera-watch/talk/276/428304?comment=727778

**Comment by camallen** [comment]
Perhaps providing a UI to remove the invalid tags will also help here.

**Comment by yshish** [comment]
@camallen asked me to share my ideas also here... 

Since there are also tag suggestions with a typo we are unable to get rid of (unless we want to go and manually remove all posts containing them - which is something I am not a fan of) and since the listed tags do not affect what appears on the top position, then what is the tag list made by the project owner good for?

It would be so much helpful if researchers/moderators were able to make a list of tags that shouldn't appear in the list - like the ones with a typo and then these tags wouldn't appear there no matter what context they were used in. Has anyone considered such an option? 

Or to have a drop-down list at each tag with options like _Add into the list of suggestions_ or _Remove from the list of suggestions_ or something like that. So if a new unwanted tag appeared we could easily to set it as unwanted, or if a new wanted tag appeared (for example if we found a species that hasn't been tagged yet) we could set it as wanted.

**Comment by camallen** [comment]
@yshish i think i have a fix in #124 that ensures the suggested tags are on top. It'll likely not be deployed till next week. Please chase me up if i haven't been in touch next week, also we can re-open if it doesn't work.

**Comment by yshish** [comment]
It would be helpful to be also able to correct miss-spelled tags that have been used for quite some time by many volunteers because of having it on the 1st position of the suggestions. 

For example on AmazonCam, we have many posts using 'Razor-billed_cu**rr**asow' instead of 'Razor-billed_cura**ss**ow'. 

If we could for example set that every tag with that specific typo would be changed automatically to the corrected one, it would make it all so much easier. There are 10 pages of results for the incorrect one, and only 1 subject with the correct one. Now the only way would be to go and re-tag all the subjects using the miss-spelled tag. And there are more such cases in other projects...

Or at least to set somewhere, that both would be considered as the same tag for the search. (I'd prefer the first option as this one would make impossible to search only the miss-spelled ones etc.)

@camallen are there any chances something like that would be ever possible - as it changing tags made by someone else? Or is there another way?

**Comment by camallen** [comment]
> If we could for example set that every tag with that specific typo would be changed automatically to the corrected one, it would make it all so much easier. 

We could do this manually in the database but i'd be against this being a something the code does as it may be like auto-correct on my phone and just wrong a lot of the time. 

> There are 10 pages of results for the incorrect one, and only 1 subject with the correct one. Now the only way would be to go and re-tag all the subjects using the miss-spelled tag. And there are more such cases in other projects...

This could be done as a one off data migration to fix the busted tags. A question, what impact does it really have, do the researchers not know how to combine the tags when looking for results? I assume this is mostly about propogating a typo, something the recent changes in suggested tag matches should fix. I can't stop a user adding their own tag, misspelt or otherwise.

**Comment by yshish** [comment]
Eeh, I didn't mean that auto-correct but such one that a researcher would be able to set (somewhere) that tag 'xzx' would be changed to 'xyx' everywhere.

As for your question, I don't know what researchers know. I guess some of them know and some of them don't. As it happens in various projects. It is just something that happens with difficult names - a misspelt species name tag is used when the animal appears for the first time and then it is being followed by everyone (due to the suggestion feature) until someone notices there's a typo...

For example on Chimp&See we just went and manually re-tagged every single subject that needed to be corrected. But since it always took us a lot of time I wondered whether there could be an easier way.

>This could be done as a one off data migration to fix the busted tags.

I am not sure what that means, sorry. Is it something every project researcher is supposed to be able to do? :) If yes, then I probably don't have to worry.
