### ISSUE TITLE
Slow posting comments and creating discussions

### ISSUE THREAD

**Issue by adammcmaster** [zooniverse/talk-api#219]
I've noticed this while testing the Azure staging deployment, but I don't think it's caused by the migration per se (possibly it's more noticeable because the new staging DB instance is smaller.

Posting new comments runs this update query which takes almost a minute in staging:
https://github.com/zooniverse/Talk-Api/blob/bfd86f952226bcf3d0efbdafd531229ff53a3021/app/models/comment.rb#L70-L88

This seems to be quite an expensive query and should probably be moved into Sidekiq.

This also affects creating new discussions and boards, since those models also `include Searchable`.

**Comment by camallen** [comment]
I’ve debugged the slow talk API queries - when serializing the talk boards it looks up the user id, login, count against the FDW users table which is a table scan. 

The issue was the FDW wrapper wasn’t using the foreign table estimates for the query planners. I ran this on the db server to update the FDW option 
```
ALTER SERVER panoptes
  OPTIONS (ADD use_remote_estimate 'true');
```
as per per https://github.com/zooniverse/talk-api/blob/192b92de87d7f4030b02becbf6f3bb19f2bd1c6d/lib/tasks/db.rake#L37
