### ISSUE TITLE
Section key naming

### ISSUE THREAD

**Issue by aweiksnar** [zooniverse/Talk-Api#39]
Section keys for project Talks are currently formatted "#{project.id}-#{project.title}". 

Would just using "#{project.id}" be okay, or is there another api-level fix available for when users edit the names of their projects?

**Comment by parrish** [comment]
It was sort of a cautious implementation since I've heard a lot of non-project related use cases for a talk section (e.g. educators forums, non-project science areas, etc.).

If we end up having multiple associations then just id alone would cause collisions. 

Project names aren't unique, so that's not good either.

We could use something like "project-#{ project.id }" if that sounds better?

**Comment by aweiksnar** [comment]
Yeah totally agree that other sections will come up. "project-#{ project.id }" would be cool for me if that works for you

**Comment by parrish** [comment]
Yep.  I'll migrate it on Monday.

**Comment by aweiksnar** [comment]
Sweet thanks!
