### ISSUE TITLE
Tracking date of last visit?

### ISSUE THREAD

**Issue by vrooje** [zooniverse/Talk-Api#44]
(Hope this is the right repo)

Does the Talk back end track when a user most recently visited Talk?

If so we could add substantial value to the front end by allowing the user to view all new posts/threads-with-new-posts since their last visit. This is something users have been asking for ever since we transitioned from standard forum software, and I admit I also find this a hugely useful feature.

I've suggested in zooniverse/Panoptes-Front-End#911 that allowing users to see the fire hose for a particular project (and maybe for all projects they've ever posted on, but I don't want to get ahead of myself) is a critical Talk feature. That's true at the moment, but it's only critical for everyone if we *can't* offer them a posts-since-last-visit option instead. If we could, then we could just let admins & mods see the fire hose.

Anyway, I figured I should check before I asked for it on the PFE repo.

**Comment by parrish** [comment]
A user technically "visits" talk every time they visit zooniverse.org, so it's not a useful metric for read tracking.

Ultimately read tracking becomes (or is requested to become) a matrix of every topic, every user that has seen the topic, and a flag that marks whether it has been read -- all of which resets on every new comment/edit.

Since it's kind of a nasty data problem, I'd like to punt it until we get the notifications system integrated.  I'm *pretty sure* that this use case will be solved with that, so I'm going to close the issue for the moment.

After that has some feedback we should definitely reevaluate though.
