### ISSUE TITLE
Zooniverse user id number not in panoptes annotations data dumps -  how to reconcile with Talk json output?

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Talk-Api#72]
One thing I noticed from the json structure is that you're using the Zooniverse user id number, that's currently not outputted in the csv raw data dumps from the panoptes project builder. So to reconcile the userid you'd have to go to the Talk thread and see the username posted.

I'm not sure what the solution is whether the json can output the ascii username or if the annotations data dumps need to provide the user id number in addition the username.  So I thought I'd post here first.

**Comment by parrish** [comment]
Currently the tags export does not include the user login (but could), the comments export does include it.  I'm happy to add it to the tags export, or allow the consumer to reference the comment export to get the username.

Since a user display name can change and a login can potentially be changed as well (under discussion), the user id is the only canonical identifier for a user.  Panoptes definitely needs to add that if it doesn't currently include it regardless of this issue.

**Comment by mschwamb** [comment]
I know they're not outputting it to a csv, I presume they're tracking by user id number, but I haven't dug into the api documentation very deeply so I don't really know. @parrish do you to raise the issue on the panoptes backend or should I about the user id number? 

I would prefer to deal with one file rather than cross reference with the comments file if it's not that difficult or time consuming on your end. I'd vote for adding in the user login.  Ultimately it's what you want to do.
