### ISSUE TITLE
How to identify all hashtags made in a notes thread about a subject?

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Talk-Api#73]
I don't understand how there could ever by taggable_id":null,"taggable_type":null," So does that mean that if you're in a conversation thread taggable_id":null,"taggable_type":null? Also does that mean for the subject notes threads if someone posts that image, but the second person who replies adds a hashtag, it wouldn't have taggable_type": "Subject"? So to get a list of subjects that have hashtags mentioned from the Notes threads I'd have to reconstruct  and find the first mention that has taggable_type": "Subject"  with the appropriate thread id?

Thanks

**Comment by parrish** [comment]
If a discussion isn't about a subject (no focus_id), a tag isn't "tagging" anything so that's null.  In other words, the person is using a tag, but not tagging something.

It does look like there is a bug that is causing comments to not properly pick up the focus from the discussion though (which does affect tags).  e.g. a discussion is started about a subject, but only the first comment is associating that focus.  That'll be fixed today in #74.
